[package]
name = "todo_list_Rust"
version = "0.1.0"
edition = "2021"

[dependencies]

serde ={ version = "1.0.210", features = ["derive"]}
serde_json = "1.0.132"
clap = { version = "4.5.20", features = ["derive"] }
chrono = { version = "0.4.38", features = ["serde"] }
